# Generated by Django 4.0.2 on 2022-04-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('quantity', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=128)),
                ('inventory', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=16)),
                ('quantity', models.CharField(max_length=20)),
                ('closed_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
