# Generated by Django 4.0.2 on 2022-04-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_inventory_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='current_quantity',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
