# Generated by Django 4.0.2 on 2022-04-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_inventory_current_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
