# Generated by Django 4.0.4 on 2022-07-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_inventory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='part_number',
            field=models.CharField(default='', max_length=512),
        ),
    ]
