# Generated by Django 4.0.4 on 2022-08-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_inventory_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='current_non_working_quantity',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='transactions',
            name='return_status',
            field=models.CharField(default='ok', max_length=20),
        ),
    ]
