# Generated by Django 4.0.4 on 2022-08-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_inventory_current_non_working_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='part_number',
            field=models.CharField(default='', max_length=512),
        ),
    ]
