# Generated by Django 4.0.4 on 2022-08-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_transactions_part_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=16)),
                ('comment', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
